# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

required = [
 "k8s.io/apiserver/pkg/endpoints/request"
]

# Fix:
#   vendor/k8s.io/kubernetes/pkg/util/parsers/parsers.go:36:16: undefined: reference.ParseNormalizedNamed
[[override]]
  name = "github.com/docker/distribution"
  branch = "master"


[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/backoff"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/helmclient"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/microerror"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/micrologger"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/versionbundle"

[[constraint]]
  version = "v0.0.1"
  name = "github.com/spf13/cobra"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.4"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.10.4"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.4"

[[constraint]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.10.4"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.4"

[[constraint]]
  name = "k8s.io/kube-aggregator"
  version = "kubernetes-1.10.4"

[[constraint]]
  branch = "master"
  name = "github.com/google/go-github"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"



[prune]
  go-tests = true
  unused-packages = true
